app:
  build: shigorath/staging/app
  command: /bin/bash shigorath/staging/app/start
  links:
    - db
  ports:
    - "3000:3000"
  volumes:
    - .:/home/deployer/application
  volumes_from:
    - gems

gems:
  image: busybox
  volumes:
    - gems

db:
  image: postgres
  ports:
    - "5432"

web:
  build: shigorath/staging/web
  ports:
    - "80:80"
  links:
    - app
