#!/usr/bin/env bash

/bin/bash while true; do echo 'im working...\n'; sleep 1; done;

#echo "Bundling gems"
#bundle install --jobs 4 --retry 3

#echo "Setting up new db if one doesn't exist"
#bin/rake db:version || { bundle exec rake db:setup; }

#echo "Running migrations"
#bin/rake db:migrate

#echo "Starting rails"
#bundle exec rails s --bind 0.0.0.0
