app:
  build: .
  dockerfile: app.dockerfile
  command: /bin/bash shigorath/local/development/app/start
  links:
    - db
  ports:
    - "3000:3000"
  volumes:
    - .:/home/developer/application
    - development_gems:/gems

db:
  image: postgres
  ports:
    - "5432"
