require 'yaml'

namespace :shig do

  def images_to_build(environment)
    settings = YAML::load(File.open("#{environment}/docker-compose.yml"))
    settings.map{|name, params| params.has_key?('build')? name:nil}.compact
  end

  def environments
    Dir.glob('*').select {|f| File.directory?(f) && f != 'shared'}
  end

  environments.each do |environment|
    namespace environment do
      desc "Basic deploy of #{environment} images"
      task :deploy do
        deploy_timestamp = Time.now.to_i
        images_to_build(environment).each do |image|
          tagged_image = "104.131.124.150:5000/#{environment}_#{image}:#{deploy_timestamp}"
          sh "docker tag #{environment}_#{image}:latest #{tagged_image}"
          sh "docker push #{tagged_image}"
        end
      end

      desc "Copy #{environment} dockerfiles to application root"
      task :copy_dockerfiles_to_root do
        images_to_build(environment).each do |image|
          cp "#{environment}/#{image}/Dockerfile", "../#{image}.dockerfile"
        end
      end

      desc "Remove copied #{environment} dockerfiles from application context"
      task :remove_dockerfiles_from_root do
        images_to_build(environment).each do |image|
          rm "../#{image}.dockerfile"
        end
      end

      desc "Build #{environment}"
      task :build => [:copy_dockerfiles_to_root] do
        Dir.chdir('../') do
          sh "docker-compose -f shigorath/#{environment}/docker-compose.yml build"
        end
        Rake::Task["shig:#{environment}:remove_dockerfiles_from_root"].invoke
      end
    end
  end
end
