require 'yaml'

namespace :shig do

  def images_to_build(environment)
    settings = YAML::load(File.open("#{environment}/docker-compose.yml"))
    settings.map{|name, params| params.has_key?('build')? name:nil}.compact
  end

  desc 'Basic deploy of staging images'
  task :staging_deploy do
    deploy_timestamp = Time.now.to_i
    images_to_build('staging').each do |image|
      tagged_image = "104.131.124.150:5000/staging_#{image}:#{deploy_timestamp}"
      sh "docker tag staging_#{image}:latest #{tagged_image}"
      sh "docker push #{tagged_image}"
    end
  end

  desc 'Mount application context'
  task :mount_context do
    images_to_build('staging').each do |image|
      rm_rf "staging/#{image}/application/"    
      mkdir "staging/#{image}/application"
      sh "sudo mount -o bind ../ staging/#{image}/application"
    end
  end 

  desc 'Unmount application context'
  task :unmount_context do
    images_to_build('staging').each do |image|
      sh "sudo umount staging/#{image}/application" unless Dir["staging/#{image}/application"].empty?
      rm_rf "staging/#{image}/application/"
    end
  end

  desc 'Build local staging'
  task :build_local_staging, [:mount_context] do
    Dir.chdir('../') do
      sh 'docker-compose -f shigorath/staging/docker-compose.yml build'
    end
  end
end
